#!/usr/bin/env node
/* Build a Google Apps Script that creates the mails as Gmail drafts.
 *
 *   node render/gmail-draft.mjs
 *
 * Gmail's compose window has no HTML source view, and pasting a rendered page
 * into it loses the mail (see email/README.md). Apps Script goes in the other
 * door: it hands Gmail the HTML and the plain-text alternative directly, and
 * the draft that appears in the account is the mail exactly as written.
 *
 * The script editor is a plain text box -- nothing renders there, so nothing
 * is baked in on the way through. Both mails are embedded whole, which is why
 * this file is generated rather than kept by hand.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';

const ROOT = resolve(new URL('..', import.meta.url).pathname);
const OUT = 'out/gmail-draft.gs';
const MAILS = [
  { key: 'reunion', fn: 'createReunionDraft', src: 'email/hepalumni-invitation',
    subject: 'Old friends, new physics' },
  { key: 'registration', fn: 'createRegistrationDraft', src: 'email/usmcc2026-registration',
    subject: 'USMCC 2026 registration is open' },
];

// A template literal holds the mail unmangled; only the two sequences that
// would end it early need escaping, and neither occurs today.
const lit = s => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';

const parts = [];
for (const m of MAILS) {
  const html = await readFile(resolve(ROOT, `${m.src}.html`), 'utf8');
  const text = await readFile(resolve(ROOT, `${m.src}.txt`), 'utf8');
  parts.push({ ...m, html, text });
  console.log(`${m.src}.html  ${html.length} bytes + ${text.length} bytes of plain text`);
}

const gs = `/* USMCC mails as Gmail drafts.
 *
 * Generated by render/gmail-draft.mjs from the files in email/. Edit those and
 * re-run; anything changed here is lost on the next build.
 *
 * To use it:
 *   1. script.google.com -> New project
 *   2. paste this whole file over whatever is in the editor, and save
 *   3. pick a function in the toolbar -- ${MAILS.map(m => m.fn + '()').join(' or ')}
 *   4. Run. Google asks for permission to manage drafts the first time; it is
 *      your own account asking about your own script.
 *   5. The draft is in Gmail, addressed to TO below, with the HTML intact and
 *      the plain-text alternative attached to it. Read it, then send it.
 *
 * Leave TO blank for a test draft to yourself. Gmail's own sending limits
 * apply, so a real list belongs in a list tool, not here.
 */

var TO = '';

${parts.map(p => `function ${p.fn}() {
  draft_(${lit(p.subject)}, HTML_${p.key.toUpperCase()}, TEXT_${p.key.toUpperCase()});
}`).join('\n\n')}

function draft_(subject, html, text) {
  var to = TO || Session.getActiveUser().getEmail();
  GmailApp.createDraft(to, subject, text, { htmlBody: html });
  Logger.log('Draft created: ' + subject + ' -> ' + to);
}

${parts.map(p => `var HTML_${p.key.toUpperCase()} = ${lit(p.html)};

var TEXT_${p.key.toUpperCase()} = ${lit(p.text)};`).join('\n\n')}
`;

await mkdir(resolve(ROOT, OUT, '..'), { recursive: true });
await writeFile(resolve(ROOT, OUT), gs);
console.log(`-> ${OUT}  (${gs.length} bytes)`);
